services:
  postgres:
    image: postgres:15-alpine
    container_name: hotel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: aruhan0077
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel_network

  redis:
    image: redis:7-alpine
    container_name: hotel_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hotel_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  hotel_network:
    driver: bridge